// <auto-generated />
using System;
using MajhiPaithani.Infrastructure.Data.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MajhiPaithani.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323055605_AddChatMessageFields")]
    partial class AddChatMessageFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.AdminLog", b =>
                {
                    b.Property<int>("ILogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ILogId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IAdminUserId")
                        .HasColumnType("int")
                        .HasColumnName("iAdminUserId");

                    b.Property<string>("SAction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sAction");

                    b.Property<string>("SDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sDescription");

                    b.HasKey("ILogId")
                        .HasName("PK__AdminLog__BBE56A58B7D3C77D");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Cart", b =>
                {
                    b.Property<int>("ICartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICartId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dUpdatedDate");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.HasKey("ICartId")
                        .HasName("PK__Cart__7B40985777FFF8B8");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.CartItem", b =>
                {
                    b.Property<int>("ICartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCartItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICartItemId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DcPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcPrice");

                    b.Property<int?>("ICartId")
                        .HasColumnType("int")
                        .HasColumnName("iCartId");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("IQuantity")
                        .HasColumnType("int")
                        .HasColumnName("iQuantity");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.HasKey("ICartItemId")
                        .HasName("PK__CartItem__FFFAC7A81BD443CD");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Category", b =>
                {
                    b.Property<int>("ICategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICategoryId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<string>("SCategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sCategoryName");

                    b.Property<string>("SDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sDescription");

                    b.HasKey("ICategoryId")
                        .HasName("PK__Categori__342A080C79EA8501");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ChatMessage", b =>
                {
                    b.Property<int>("IMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMessageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMessageId"));

                    b.Property<bool>("BIsDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDelivered");

                    b.Property<bool>("BIsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsRead");

                    b.Property<DateTime?>("DDeliveredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeliveredDate");

                    b.Property<DateTime?>("DReadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dReadDate");

                    b.Property<DateTime?>("DSentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dSentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IChatRoomId")
                        .HasColumnType("int")
                        .HasColumnName("iChatRoomId");

                    b.Property<int?>("IReceiverUserId")
                        .HasColumnType("int")
                        .HasColumnName("iReceiverUserId");

                    b.Property<int?>("ISenderUserId")
                        .HasColumnType("int")
                        .HasColumnName("iSenderUserId");

                    b.Property<string>("SAttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sAttachmentUrl");

                    b.Property<string>("SMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sMessage");

                    b.HasKey("IMessageId")
                        .HasName("PK__ChatMess__93BB44EB74366B16");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ChatRoom", b =>
                {
                    b.Property<int>("IChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iChatRoomId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IChatRoomId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.HasKey("IChatRoomId")
                        .HasName("PK__ChatRoom__DB1BA504B08C0155");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Coupon", b =>
                {
                    b.Property<int>("ICouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCouponId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICouponId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dEndDate");

                    b.Property<DateTime?>("DStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dStartDate");

                    b.Property<decimal?>("DcDiscountAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcDiscountAmount");

                    b.Property<string>("SCouponCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sCouponCode");

                    b.HasKey("ICouponId")
                        .HasName("PK__Coupons__FEF61934271E728B");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Customer", b =>
                {
                    b.Property<int>("ICustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICustomerId"));

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("ICustomerId")
                        .HasName("PK__Customer__EA0B906C0EBFFEED");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.CustomerAddress", b =>
                {
                    b.Property<int>("IAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iAddressId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IAddressId"));

                    b.Property<bool?>("BIsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDefault");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<string>("SAddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sAddressLine1");

                    b.Property<string>("SAddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sAddressLine2");

                    b.Property<string>("SCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sCity");

                    b.Property<string>("SFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sFullName");

                    b.Property<string>("SPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sPhoneNumber");

                    b.Property<string>("SPincode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sPincode");

                    b.Property<string>("SState")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sState");

                    b.HasKey("IAddressId")
                        .HasName("PK__Customer__C6E4D70D1247776F");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.CustomizationRequest", b =>
                {
                    b.Property<int>("ICustomizationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iCustomizationRequestId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICustomizationRequestId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<string>("SCustomizationDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sCustomizationDetails");

                    b.Property<string>("SReferenceImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sReferenceImageUrl");

                    b.Property<string>("SStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sStatus");

                    b.HasKey("ICustomizationRequestId")
                        .HasName("PK__Customiz__99534C10A0E6A198");

                    b.ToTable("CustomizationRequests");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Design", b =>
                {
                    b.Property<int>("IDesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDesignId"));

                    b.Property<bool?>("BIsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int");

                    b.Property<string>("SDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDesignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDesignType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDesignId");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Location", b =>
                {
                    b.Property<int>("ILocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iLocationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ILocationId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sCity");

                    b.Property<string>("SDistrict")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sDistrict");

                    b.Property<string>("SPincode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sPincode");

                    b.Property<string>("SState")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sState");

                    b.HasKey("ILocationId")
                        .HasName("PK__Location__1AC9AF763EAAB00E");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Notification", b =>
                {
                    b.Property<int>("INotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iNotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("INotificationId"));

                    b.Property<bool?>("BIsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsRead");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.Property<string>("SMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sMessage");

                    b.Property<string>("SNotificationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sNotificationType");

                    b.Property<string>("STitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("sTitle");

                    b.HasKey("INotificationId")
                        .HasName("PK__Notifica__84A3165B3A29EE20");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Order", b =>
                {
                    b.Property<int>("IOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iOrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IOrderId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeliveryDate");

                    b.Property<DateTime?>("DOrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dOrderDate");

                    b.Property<decimal?>("DcTotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcTotalAmount");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<string>("SOrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sOrderStatus");

                    b.Property<string>("SPaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sPaymentStatus");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("IOrderId")
                        .HasName("PK__Orders__F354140FD000231A");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.OrderCoupon", b =>
                {
                    b.Property<int>("IOrderCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iOrderCouponId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IOrderCouponId"));

                    b.Property<decimal?>("DcDiscountAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcDiscountAmount");

                    b.Property<int?>("ICouponId")
                        .HasColumnType("int")
                        .HasColumnName("iCouponId");

                    b.Property<int?>("IOrderId")
                        .HasColumnType("int")
                        .HasColumnName("iOrderId");

                    b.HasKey("IOrderCouponId")
                        .HasName("PK__OrderCou__120A39F357494FD6");

                    b.ToTable("OrderCoupons");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.OrderItem", b =>
                {
                    b.Property<int>("IOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iOrderItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IOrderItemId"));

                    b.Property<decimal?>("DcPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcPrice");

                    b.Property<decimal?>("DcTotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcTotalPrice");

                    b.Property<int?>("IOrderId")
                        .HasColumnType("int")
                        .HasColumnName("iOrderId");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("IQuantity")
                        .HasColumnType("int")
                        .HasColumnName("iQuantity");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.HasKey("IOrderItemId")
                        .HasName("PK__OrderIte__02504D79E65F42FB");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Payment", b =>
                {
                    b.Property<int>("IPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iPaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IPaymentId"));

                    b.Property<DateTime?>("DPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dPaymentDate");

                    b.Property<decimal?>("DcAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcAmount");

                    b.Property<int?>("IOrderId")
                        .HasColumnType("int")
                        .HasColumnName("iOrderId");

                    b.Property<string>("SPaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sPaymentMethod");

                    b.Property<string>("SPaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sPaymentStatus");

                    b.Property<string>("STransactionId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("sTransactionId");

                    b.HasKey("IPaymentId")
                        .HasName("PK__Payments__D6E7F12201069949");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("IProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IProductId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsCustomizationAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsCustomizationAvailable");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<DateTime?>("DUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dUpdatedDate");

                    b.Property<decimal?>("DcBasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dcBasePrice");

                    b.Property<int?>("ICategoryId")
                        .HasColumnType("int")
                        .HasColumnName("iCategoryId");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.Property<string>("SColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sColor");

                    b.Property<string>("SDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sDescription");

                    b.Property<string>("SDesignType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDesignType");

                    b.Property<string>("SFabric")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sFabric");

                    b.Property<string>("SProductTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("sProductTitle");

                    b.HasKey("IProductId")
                        .HasName("PK__Products__2A611C8457938B60");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ProductImage", b =>
                {
                    b.Property<int>("IImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iImageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IImageId"));

                    b.Property<bool?>("BIsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsPrimary");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<string>("SImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sImageUrl");

                    b.Property<int>("sellerId")
                        .HasColumnType("int");

                    b.HasKey("IImageId")
                        .HasName("PK__ProductI__EEA8AE34B628B178");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ProductReview", b =>
                {
                    b.Property<int>("IReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iReviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IReviewId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("IRating")
                        .HasColumnType("int")
                        .HasColumnName("iRating");

                    b.Property<string>("SComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sComment");

                    b.HasKey("IReviewId")
                        .HasName("PK__ProductR__2339F98883394C5A");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ProductTag", b =>
                {
                    b.Property<int>("ITagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iTagId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ITagId"));

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("STagName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sTagName");

                    b.HasKey("ITagId")
                        .HasName("PK__ProductT__40490F4C826BB1FE");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ProductTagMapping", b =>
                {
                    b.Property<int>("IMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMappingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMappingId"));

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("ITagId")
                        .HasColumnType("int")
                        .HasColumnName("iTagId");

                    b.HasKey("IMappingId")
                        .HasName("PK__ProductT__51ECBB1DBCEF2A24");

                    b.ToTable("ProductTagMapping", (string)null);
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.ProductView", b =>
                {
                    b.Property<int>("IViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iViewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IViewId"));

                    b.Property<DateTime?>("DViewedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dViewedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("IViewId")
                        .HasName("PK__ProductV__D937E72EF6D288E0");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Productdemo", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockAvailable")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Productdemos");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Role", b =>
                {
                    b.Property<int>("IRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IRoleId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sRoleName");

                    b.HasKey("IRoleId")
                        .HasName("PK__Roles__D69F8C9E6DE6E80B");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.SearchHistory", b =>
                {
                    b.Property<int>("ISearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iSearchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISearchId"));

                    b.Property<DateTime?>("DSearchDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dSearchDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.Property<string>("SSearchKeyword")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("sSearchKeyword");

                    b.HasKey("ISearchId")
                        .HasName("PK__SearchHi__1D51F56AC4A9082D");

                    b.ToTable("SearchHistory", (string)null);
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Seller", b =>
                {
                    b.Property<int>("ISellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISellerId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<bool?>("BIsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsVerified");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<DateTime?>("DUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dUpdatedDate");

                    b.Property<int?>("ILocationId")
                        .HasColumnType("int")
                        .HasColumnName("iLocationId");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.Property<string>("SBusinessDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SShopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SShopDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sShopDescription");

                    b.Property<string>("SShopName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sShopName");

                    b.Property<string>("SState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISellerId")
                        .HasName("PK__Sellers__99BF1FD4CE2D8F7E");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.SellerBankDetail", b =>
                {
                    b.Property<int>("IbankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IBankDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IbankDetailId"));

                    b.Property<DateTime?>("DcreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DCreatedDate")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DupdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DUpdatedDate");

                    b.Property<int?>("IsellerId")
                        .HasColumnType("int")
                        .HasColumnName("ISellerId");

                    b.Property<string>("SaccountHolderName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SAccountHolderName");

                    b.Property<string>("SaccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SAccountNumber");

                    b.Property<string>("SbankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SBankName");

                    b.Property<string>("Sifsccode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SIFSCCode");

                    b.HasKey("IbankDetailId")
                        .HasName("PK__SellerBa__AD3D267EE3DBF786");

                    b.ToTable("SellerBankDetails");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.SellerDocument", b =>
                {
                    b.Property<int>("IDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iDocumentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDocumentId"));

                    b.Property<bool?>("BIsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsVerified");

                    b.Property<DateTime?>("DUploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dUploadedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.Property<string>("SDocumentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sDocumentType");

                    b.Property<string>("SDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sDocumentUrl");

                    b.HasKey("IDocumentId")
                        .HasName("PK__SellerDo__336026B2D7BB52B8");

                    b.ToTable("SellerDocuments");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.SellerReview", b =>
                {
                    b.Property<int>("ISellerReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iSellerReviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISellerReviewId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ICustomerId")
                        .HasColumnType("int")
                        .HasColumnName("iCustomerId");

                    b.Property<int?>("IRating")
                        .HasColumnType("int")
                        .HasColumnName("iRating");

                    b.Property<int?>("ISellerId")
                        .HasColumnType("int")
                        .HasColumnName("iSellerId");

                    b.Property<string>("SComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sComment");

                    b.HasKey("ISellerReviewId")
                        .HasName("PK__SellerRe__95A25099EF6AD721");

                    b.ToTable("SellerReviews");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("IUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IUserId"));

                    b.Property<bool?>("BIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("BIsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bIsDeleted");

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DDeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dDeletedDate");

                    b.Property<DateTime?>("DUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dUpdatedDate");

                    b.Property<int?>("IRoleId")
                        .HasColumnType("int")
                        .HasColumnName("iRoleId");

                    b.Property<bool?>("IsSellerProfileComplete")
                        .HasColumnType("bit")
                        .HasColumnName("IsSellerProfileComplete");

                    b.Property<string>("SEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sEmail");

                    b.Property<string>("SFirstName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sFirstName");

                    b.Property<string>("SLastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sLastName");

                    b.Property<string>("SPasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sPasswordHash");

                    b.Property<string>("SPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sPhoneNumber");

                    b.HasKey("IUserId")
                        .HasName("PK__Users__BA95FFB1C0146444");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MajhiPaithani.Infrastructure.Entities.Wishlist", b =>
                {
                    b.Property<int>("IWishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iWishlistId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IWishlistId"));

                    b.Property<DateTime?>("DCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IProductId")
                        .HasColumnType("int")
                        .HasColumnName("iProductId");

                    b.Property<int?>("IUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("IWishlistId")
                        .HasName("PK__Wishlist__AD0A7D289C37FC4F");

                    b.ToTable("Wishlist", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
