name: Deploy to EC2 IIS (Final)

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Debug Publish
      run: ls -la publish

    - name: Test SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Connected"
          hostname

    - name: Stop App Pool
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          powershell -Command "Import-Module WebAdministration; Stop-WebAppPool -Name 'MajhiPaithani'"

    - name: Clean IIS Folder
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          powershell -Command "Remove-Item -Path 'C:\inetpub\MajhiPaithaniApp\*' -Recurse -Force -ErrorAction SilentlyContinue"

    - name: Upload Files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "publish/*"
        target: "/c$/inetpub/MajhiPaithaniApp"

    - name: Verify Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          powershell -Command "Get-ChildItem 'C:\inetpub\MajhiPaithaniApp'"

    - name: Start App Pool
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 15.207.106.250
        username: Administrator
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          powershell -Command "Import-Module WebAdministration; Start-WebAppPool -Name 'MajhiPaithani'"

    - name: Done
      run: echo "Deployment Successful 🚀"
